// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhqD444kL6hjx8be_OxwgRRLRo2gwFysU',
    appId: '1:358986040807:web:ce8fe3a9ca94398d9c6942',
    messagingSenderId: '358986040807',
    projectId: 'my-firebase-project-6b329',
    authDomain: 'my-firebase-project-6b329.firebaseapp.com',
    storageBucket: 'my-firebase-project-6b329.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQw_9oPyjRNCDyhhBtb7hH3qWj2L64GUg',
    appId: '1:358986040807:android:9f5013035ccf10819c6942',
    messagingSenderId: '358986040807',
    projectId: 'my-firebase-project-6b329',
    storageBucket: 'my-firebase-project-6b329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv5FkXDOF5ifOCZATrRmUKXwxPDCRISzs',
    appId: '1:358986040807:ios:7623a4a2cf86a3459c6942',
    messagingSenderId: '358986040807',
    projectId: 'my-firebase-project-6b329',
    storageBucket: 'my-firebase-project-6b329.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv5FkXDOF5ifOCZATrRmUKXwxPDCRISzs',
    appId: '1:358986040807:ios:640db80ed2818c399c6942',
    messagingSenderId: '358986040807',
    projectId: 'my-firebase-project-6b329',
    storageBucket: 'my-firebase-project-6b329.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
